name: Windows x64 Build (CatuGram)

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  windows:
    name: Windows x64 Qt6 Build
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64]
        qt: [qt6]
        generator: ["Ninja Multi-Config"]

    env:
      UPLOAD_ARTIFACT: "true"
      ONLY_CACHE: "false"
      PREPARE_PATH: "Telegram/build/prepare/prepare.py"

    defaults:
      run:
        shell: cmd

    steps:
      - name: Prepare directories.
        run: |
          mkdir %userprofile%\TBuild\Libraries
          mklink /d %GITHUB_WORKSPACE%\TBuild %userprofile%\TBuild
          echo TBUILD=%GITHUB_WORKSPACE%\TBuild>>%GITHUB_ENV%
          echo LibrariesPath=%GITHUB_WORKSPACE%\TBuild\Libraries\win64>>%GITHUB_ENV%

      - name: Get repository name.
        shell: bash
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Clone repository.
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: ${{ env.TBUILD }}\${{ env.REPO_NAME }}

      - name: First set up.
        shell: bash
        run: |
          DOCPATH=$TBUILD/$REPO_NAME/docs/building-win.md
          SDK="$(grep "SDK version" $DOCPATH | sed -r 's/.*\*\*(.*)\*\* SDK version.*/\1/')"
          echo "SDK=$SDK" >> $GITHUB_ENV

          sed -i '/CMAKE_${lang}_FLAGS_DEBUG_INIT/s/${_Zi}//' "$PROGRAMFILES"/CMake/share/cmake*/Modules/Platform/Windows-MSVC.cmake

          echo "$(sha256sum $TBUILD/$REPO_NAME/$PREPARE_PATH | awk '{ print $1 }')" >> CACHE_KEY.txt
          echo "$SDK" >> CACHE_KEY.txt
          echo "CACHE_KEY=$(sha256sum CACHE_KEY.txt | awk '{ print $1 }')" >> $GITHUB_ENV

          echo "Configurate git for cherry-picks."
          git config --global user.email "build@catugram.local"
          git config --global user.name "CatuGram Builder"

      - uses: ilammy/msvc-dev-cmd@v1
        name: Visual Studio Command Prompt
        with:
          arch: x64
          sdk: ${{ env.SDK }}

      - name: NuGet sources.
        run: |
          nuget sources Disable -Name "Microsoft Visual Studio Offline Packages"
          nuget sources Add -Source https://api.nuget.org/v3/index.json & exit 0

      - name: ThirdParty cache.
        id: cache-third-party
        uses: actions/cache@v4
        with:
          path: ${{ env.TBUILD }}\ThirdParty
          key: ${{ runner.OS }}-x64-third-party-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.OS }}-x64-third-party-

      - name: Libraries cache.
        id: cache-libs
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.LibrariesPath }}\*
            !${{ env.LibrariesPath }}\cache_keys
            !${{ env.LibrariesPath }}\[qQ]t[_-]*
            ${{ env.LibrariesPath }}\cache_keys\*
            !${{ env.LibrariesPath }}\cache_keys\[qQ]t[_-]*
          key: ${{ runner.OS }}-x64-libs-v2-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.OS }}-x64-libs-v2-

      - name: Qt cache.
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.LibrariesPath }}\[qQ]t[_-]*
            ${{ env.LibrariesPath }}\cache_keys\[qQ]t[_-]*
          key: ${{ runner.OS }}-x64-qt6-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.OS }}-x64-qt6-

      - name: Prepare Libraries.
        run: |
          %TBUILD%\%REPO_NAME%\Telegram\build\prepare\win.bat skip-release silent qt6

      - name: Configure CMake and Telegram Desktop.
        shell: bash
        run: |
          echo "TDESKTOP_BUILD_API=-D TDESKTOP_API_ID=17349 -D TDESKTOP_API_HASH=344583e45741c457fe1862106095a5eb" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=CatuGram-Desktop-Win64-Portable" >> $GITHUB_ENV

      - name: Free up disk space.
        shell: bash
        run: find $LibrariesPath '(' '(' ! '(' -name '*.lib' -o -name '*.a' -o -name '*.exe' -o -name '*.h' -o -name '*.hpp' -o -name '*.inc' -o -name '*.cmake' -o -name '*.pc' -o -path '*/include/*' -o -path '*/objects-*' -o -path '*/cache_keys/*' -o -path '*/patches/*' -o -path '*/nv-codec-headers/*' ')' -type f ')' -o -empty ')' -delete

      - name: Build Telegram Desktop (Debug/Release).
        run: |
          cd %TBUILD%\%REPO_NAME%\Telegram

          call configure.bat ^
          -G "Ninja Multi-Config" ^
          qt6 ^
          %TDESKTOP_BUILD_API% ^
          -D CMAKE_CONFIGURATION_TYPES=Debug ^
          -D CMAKE_COMPILE_WARNING_AS_ERROR=OFF ^
          -D CMAKE_MSVC_DEBUG_INFORMATION_FORMAT= ^
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=ON ^
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=ON

          cmake --build ..\out --config Debug --parallel

      - name: Prepare Portable Artifact.
        run: |
          set OUT=%TBUILD%\%REPO_NAME%\out\Debug
          mkdir %GITHUB_WORKSPACE%\artifact
          if exist %OUT%\Telegram.exe copy %OUT%\Telegram.exe %GITHUB_WORKSPACE%\artifact\CatuGram.exe
          if exist %OUT%\Telegram.exe copy %OUT%\Telegram.exe %GITHUB_WORKSPACE%\artifact\Telegram.exe
          if exist %OUT%\Updater.exe copy %OUT%\Updater.exe %GITHUB_WORKSPACE%\artifact\Updater.exe

      - name: Upload Build Artifact.
        uses: actions/upload-artifact@v4
        with:
          name: CatuGram-Desktop-Win64-Portable
          path: artifact\
